version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
  assignees:
    - "angristan"
  reviewers:
    - "angristan"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
